name: privacyidea_authenticator
description: An OTP Authenticator App for privacyIDEA Authentication Server.
homepage: https://netknights.it
repository: https://github.com/privacyidea/pi-authenticator
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.3.0+403008 # TODO Set the right version number 
# version: major.minor.build          + 2x major|2x minor|3x build
# version: version number             + build number (optional)
# android: build-name                 + versionCode
# iOS    : CFBundleShortVersionString + CFBundleVersion

environment:
  sdk: '>=3.0.0 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4

  # intl: ^0.18.0
  permission_handler: ^11.0.0

  logger: ^2.0.0

  uuid: ^4.0.0
  
  mutex: ^3.0.0
  hex: ^0.2.0
  base32: ^2.1.1
  pointycastle: ^3.7.3
  asn1lib: ^1.5.0 
  encrypt: ^5.0.3
  cryptography: ^2.7.0
  otp: ^3.0.1

  file_selector: ^1.0.2
  flutter_secure_storage: ^9.0.0
  
  package_info_plus: ^5.0.1
  device_info_plus: ^9.0.3
  easy_dynamic_theme: ^2.2.0
  # flutter_markdown: ^0.6.8

  uni_links: ^0.5.1
  url_launcher: ^6.0.12
  http: ^1.1.0
  connectivity_plus: ^5.0.1
  flutter_mailer: ^2.1.1
  
  # collection: ^1.17.2
  # # flare_flutter: ^3.0.2
  # path_provider: ^2.0.15

  flutter_riverpod: ^2.3.6
  flutterlifecyclehooks: ^4.0.0

  shared_preferences: ^2.2.0
  # flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.0.0
  # extended_nested_scroll_view: ^6.1.2
  
  local_auth: ^2.1.6
  local_auth_ios: ^1.1.3
  local_auth_android: ^1.0.32

  json_annotation: ^4.8.1
  # equatable: ^2.0.5
  # arrow_path: ^3.1.0

  image: ^4.1.6
  ## mobile_scanner: ^4.0.0
  zxing2: ^0.2.1
  
  home_widget: ^0.4.1
  app_minimizer: ^1.0.0+2

  # Icons
  lottie: ^3.0.0
  fluentui_system_icons: ^1.1.223
  material_design_icons_flutter: ^7.0.7296
  # Widgets
  flutter_slidable: ^3.0.0
  expandable: ^5.0.1
  camera: ^0.10.5+9
  flutter_zxing: ^1.5.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  test: ^1.24.1
  protobuf: ^3.1.0


  # dependencies to serialize objects to json
  build_runner: ^2.4.6
  json_serializable: ^6.0.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # Automatically create files used for localization
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - res/logo/
    - CHANGELOG.md
    - res/guide/
    - res/gif/
    - res/lottie/
    - res/rive/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_launcher_icons:
  android: true
  image_path: "customization/temp/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "customization/temp/app_icon_adaptive.png"
  ios: true
  image_path_ios: "customization/temp/app_icon_ios.png"
  remove_alpha_ios: false # default false